### ISSUE TITLE
Bug: preview or thumbnail not shown in Finder when keyword 'OBJECT' is short 

### ISSUE THREAD

**Issue by niu541412** [onekiloparsec/QLFits#6]
the log of `qlmanage -p test.fits` is

> Testing Quick Look preview with files:
	test.fits
 GeneratePreviewForURL.m                  37: [QLFits3] Previewing file:///Users/jomic/Downloads/apk/test.fits
 GeneratePreviewForURL.m                  66: [QLFits3] Open FITS file
 GeneratePreviewForURL.m                 113: [QLFits3] Loading FITS Data of HDU at index 0
 GeneratePreviewForURL.m                 124: Creating HDU image
 GeneratePreviewForURL.m                 143: [QLFits3] Drawing a 2D image
Segmentation fault: 11

The keyword of test.fits is 'GC130', when I modified it to ,e.g., 'GC130XXXXX', this plugin works again.
This fits file is created by the latest Astropy package (I don't think it matters), my macOS is Big Sur.

**Comment by onekiloparsec** [comment]
Ah that an interesting one! I've not opened the project since a long time, but I can try. Would you mind sending me the faulty fits file on my email address? cedric @ onekiloparsec.dev

**Comment by onekiloparsec** [comment]
3 years later... amazing perseverance. Should we close this?
