### ISSUE TITLE
Sequoia 15 installation issues

### ISSUE THREAD

**Issue by shuwn** [onekiloparsec/QLFits#8]
**Platform**
Sequoia 15.0 (24A335)

**Version**
QLFits3 3.2.2
Homebrew 4.3.24

**What happened?**
1. The installation instructions need to be updated as brew cask is no longer available.
<img width="980" alt="image" src="https://github.com/user-attachments/assets/4a527467-ce40-4ad6-8745-ac76ccb9822c">
2. The quicklookd process fails to execute QLFits3 without any error messages.
<img width="1712" alt="Snipaste_2024-10-01_18-22-47" src="https://github.com/user-attachments/assets/cd5db58c-2e37-49a8-9511-9fadb1231d95">

**Comment by niu541412** [comment]
- `brew cask install package` is a deprecated command, you can use `brew install package` or `brew install package --cask` instead.
- I've created a new PR with bug fixing and Apple Silicon architecture support. The author merged it but didn't release the binary. However, you can find them with my build at https://github.com/niu541412/QLFits/releases and install it manually. I don't have a Mac machine with the latest macOS, so I haven't tested enough. BTW, I don't have an Apple developer account, you must trust my build to use it.

**Comment by onekiloparsec** [comment]
Hi. Sorry, for not having the time to dig into these issues anymore. I would suggest trying the new and maintained plugin "QuickFits": https://apps.apple.com/us/app/quickfits/id1551075981?mt=12
